# Generated by Django 4.2.13 on 2024-07-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('cep', models.CharField(max_length=8)),
                ('country', models.CharField(choices=[('Rio de Janeiro', 'Rio de Janeiro'), ('Niterói', 'Niterói')], max_length=20)),
                ('city', models.CharField(choices=[('Brasil', 'Brasil')], max_length=20)),
                ('street', models.CharField(max_length=50)),
                ('address_number', models.IntegerField()),
                ('address_complement', models.CharField(max_length=50)),
                ('tel_ddd', models.CharField(max_length=2)),
                ('tel', models.CharField(max_length=9)),
                ('gender', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro')], max_length=20)),
                ('bio', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('cep', models.CharField(max_length=8)),
                ('country', models.CharField(choices=[('Rio de Janeiro', 'Rio de Janeiro'), ('Niterói', 'Niterói')], max_length=20)),
                ('city', models.CharField(choices=[('Brasil', 'Brasil')], max_length=20)),
                ('street', models.CharField(max_length=50)),
                ('address_number', models.IntegerField()),
                ('address_complement', models.CharField(max_length=50)),
                ('tel_ddd', models.CharField(max_length=2)),
                ('tel', models.CharField(max_length=9)),
                ('gender', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro')], max_length=20)),
                ('bio', models.CharField(max_length=200)),
            ],
        ),
    ]
